apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: provider-k8s-webhook
  namespace: {{ .Release.Namespace }}
spec:
  secretName: provider-k8s-webhook-ca
  dnsNames:
    - provider-k8s-webhook.{{ .Release.Namespace }}.svc
    - provider-k8s-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: provider-k8s-webhook
