apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: provider-k8s-webhook
  annotations:
    "cert-manager.io/inject-ca-from": "{{ .Release.Namespace}}/provider-k8s-webhook"
webhooks:
  - name: webhook.aerf.io
    rules:
      - apiGroups:
          - "aerf.io"
          - k8s.aerf.io
        apiVersions:
          - "v1alpha1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - "*/*"
    admissionReviewVersions: ["v1"]
    # This webhook only accepts v1 cert-manager resources.
    # Equivalent matchPolicy ensures that non-v1 resource requests are sent to
    # this webhook (after the resources have been converted to v1).
    matchPolicy: Equivalent
    timeoutSeconds: 30
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: provider-k8s-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate
        port: 443
