#apiVersion: v1
#kind: Secret
#metadata:
#  namespace: crossplane-system
#  name: example-provider-secret
#type: Opaque
#data:
  # credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: aerf.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: InjectedIdentity
#    secretRef:
#      namespace: crossplane-system
#      name: example-provider-secret
#      key: credentials
