apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-k8s
  annotations:
#    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/aerfio/provider-k8s
    meta.crossplane.io/license: Apache-2.0
#    meta.crossplane.io/description: |
#      A lambda that can be used to create Crossplane providers.
